# Site settings
title: Murfad Khan
email: mfu.khan@outlook.com
description: "Personal Blog of Murfad Khan, "
baseurl: ""
url: "http://murfadkhan.com"

# Build settings
markdown: kramdown
permalink: pretty
